#!/usr/bin/env python3
import sys
from pathlib import Path

import mujoco
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
mjb = sys.argv[1] if len(sys.argv) > 1 else str(ROOT / "assets/m2_metal.xml")
out = sys.argv[2] if len(sys.argv) > 2 else str(ROOT / "web/m2_model_const.h")
m = mujoco.MjModel.from_xml_path(mjb)

def carr(name, a, t="double", fmt="%.17g"):
    a = np.asarray(a).ravel()
    body = ", ".join((str(int(x)) if t == "int" else fmt % x) for x in a)
    return f"static const {t} {name}[{a.size}] = {{{body}}};"

L = ["// AUTO-GENERATED by tools/dump_m2_model_const.py — do not edit.",
     "// Complete M2 model constants for the host/WASM single-env stepper.",
     "#pragma once", ""]
L += [f"#define HC_NQ {m.nq}", f"#define HC_NV {m.nv}", f"#define HC_NU {m.nu}",
      f"#define HC_NBODY {m.nbody}", f"#define HC_NJNT {m.njnt}",
      f"#define HC_NM {m.nM}",
      f"static const double HC_TIMESTEP_DEFAULT = {m.opt.timestep:.17g};",
      carr("hc_gravity", m.opt.gravity), ""]
# bodies
L += [carr("hc_body_jntadr", m.body_jntadr, "int"),
      carr("hc_body_jntnum", m.body_jntnum, "int"),
      carr("hc_body_parentid", m.body_parentid, "int"),
      carr("hc_body_rootid", m.body_rootid, "int"),
      carr("hc_body_dofadr", m.body_dofadr, "int"),
      carr("hc_body_dofnum", m.body_dofnum, "int"),
      carr("hc_body_pos", m.body_pos),
      carr("hc_body_quat", m.body_quat),
      carr("hc_body_ipos", m.body_ipos),
      carr("hc_body_iquat", m.body_iquat),
      carr("hc_body_mass", m.body_mass),
      carr("hc_body_inertia", m.body_inertia),
      carr("hc_body_subtreemass", m.body_subtreemass), ""]
# joints
L += [carr("hc_jnt_type", m.jnt_type, "int"),
      carr("hc_jnt_qposadr", m.jnt_qposadr, "int"),
      carr("hc_jnt_dofadr", m.jnt_dofadr, "int"),
      carr("hc_jnt_bodyid", m.jnt_bodyid, "int"),
      carr("hc_jnt_axis", m.jnt_axis),
      carr("hc_jnt_pos", m.jnt_pos),
      carr("hc_jnt_actfrclimited", m.jnt_actfrclimited, "int"),
      carr("hc_jnt_actfrcrange", m.jnt_actfrcrange), ""]
# dofs
# NOTE: Zero out floating-base DOFs (0-5) for damping and frictionloss.
dof_damping = m.dof_damping.copy()
dof_frictionloss = m.dof_frictionloss.copy()
for i in range(m.nv):
    if m.dof_bodyid[i] == 1 and i < 6:  # floating base DOFs
        dof_damping[i] = 0.0
        dof_frictionloss[i] = 0.0

L += [carr("hc_dof_Madr", m.dof_Madr, "int"),
      carr("hc_dof_parentid", m.dof_parentid, "int"),
      carr("hc_dof_bodyid", m.dof_bodyid, "int"),
      carr("hc_dof_armature", m.dof_armature),
      carr("hc_dof_damping", dof_damping),
      carr("hc_qpos0", m.qpos0), ""]
# actuators
L += [carr("hc_act_ctrlrange", m.actuator_ctrlrange),
      carr("hc_act_trnid", m.actuator_trnid[:, 0] if m.nu > 0 else [], "int"),
      carr("hc_act_gain0", m.actuator_gainprm[:, 0] if m.nu > 0 else []),
      carr("hc_act_bias1", m.actuator_biasprm[:, 1] if m.nu > 0 else []),
      carr("hc_act_bias2", m.actuator_biasprm[:, 2] if m.nu > 0 else []), ""]
# home keyframe
home_qpos = [0.0, 0.0, 0.32, 1.0, 0.0, 0.0, 0.0, 0.0, 0.7, -1.4, 0.0, 0.7, -1.4, 0.0, 0.7, -1.4, 0.0, 0.7, -1.4]
L += [carr("hc_key_qpos", home_qpos),
      f"#define HC_JNT_FREE {int(mujoco.mjtJoint.mjJNT_FREE)}", ""]
# contact constants
L += [f"#define HC_NGEOM {m.ngeom}", f"#define HC_NPAIR {m.npair}",
      f"#define HC_GEOM_PLANE {int(mujoco.mjtGeom.mjGEOM_PLANE)}",
      f"#define HC_GEOM_SPHERE {int(mujoco.mjtGeom.mjGEOM_SPHERE)}",
      f"#define HC_GEOM_BOX {int(mujoco.mjtGeom.mjGEOM_BOX)}",
      f"#define HC_GEOM_CAPSULE {int(mujoco.mjtGeom.mjGEOM_CAPSULE)}",
      f"static const double HC_MEANINERTIA = {m.stat.meaninertia:.17g};",
      f"static const double HC_IMPRATIO = {m.opt.impratio:.17g};",
      f"static const double HC_TOL = {m.opt.tolerance:.17g};",
      f"static const double HC_LSTOL = {m.opt.ls_tolerance:.17g};",
      f"#define HC_ITER_DEFAULT {int(m.opt.iterations)}",
      f"#define HC_LS_ITER_DEFAULT {int(m.opt.ls_iterations)}", ""]

_gcol = np.array([(m.mat_rgba[m.geom_matid[g]][:3] if m.geom_matid[g] >= 0
                   else m.geom_rgba[g][:3]) for g in range(m.ngeom)])
L += [carr("hc_geom_bodyid", m.geom_bodyid, "int"),
      carr("hc_geom_type", m.geom_type, "int"),
      carr("hc_geom_dataid", m.geom_dataid, "int"),
      carr("hc_geom_pos", m.geom_pos), carr("hc_geom_quat", m.geom_quat),
      carr("hc_geom_size", m.geom_size),
      carr("hc_geom_color", _gcol, fmt="%.6g"), ""]
if m.npair > 0:
    L += [carr("hc_pair_geom1", m.pair_geom1, "int"),
          carr("hc_pair_geom2", m.pair_geom2, "int"),
          carr("hc_pair_dim", m.pair_dim, "int"),
          carr("hc_pair_margin", m.pair_margin), carr("hc_pair_gap", m.pair_gap),
          carr("hc_pair_friction", m.pair_friction),
          carr("hc_pair_solref", m.pair_solref),
          carr("hc_pair_solimp", m.pair_solimp), ""]
else:
    L += ["static const int hc_pair_geom1[1]={0}, hc_pair_geom2[1]={0}, hc_pair_dim[1]={0};",
          "static const double hc_pair_margin[1]={0}, hc_pair_gap[1]={0}, hc_pair_friction[5]={0}, hc_pair_solref[2]={0}, hc_pair_solimp[5]={0};"]

L += [carr("hc_dof_frictionloss", dof_frictionloss),
      carr("hc_dof_solref", m.dof_solref), carr("hc_dof_solimp", m.dof_solimp),
      carr("hc_dof_invweight0", m.dof_invweight0),
      carr("hc_body_invweight0", m.body_invweight0), ""]
L += [carr("hc_jnt_limited", m.jnt_limited, "int"),
      carr("hc_jnt_range", m.jnt_range), carr("hc_jnt_margin", m.jnt_margin),
      carr("hc_jnt_solref", m.jnt_solref), carr("hc_jnt_solimp", m.jnt_solimp), ""]

Path(out).parent.mkdir(parents=True, exist_ok=True)
Path(out).write_text("\n".join(L) + "\n")
print(f"wrote {out}: nq={m.nq} nv={m.nv} nbody={m.nbody} njnt={m.njnt} nM={m.nM}")

